/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD.HTW.App;

import TD.HTW.CommandPatterns.CommandFactory;
import TD.HTW.CommandPatterns.ICommand;

import java.util.LinkedList;

public class App {
    public static void main(String[] args) {
        IConsole console = new Console();

        CommandFactory cmdFactory = new CommandFactory(console);
        LinkedList<ICommand> commands = cmdFactory.returnsCommands();

        do {
            printCLIOptions(commands);
            ICommand cmd = selectCLIOption(console, commands);
            cmd.execute();
        } while (true);
    }

    private static ICommand selectCLIOption(IConsole console, LinkedList<ICommand> cmds) {
        do {
            int idx = console.readInteger("Please select an option: ");
            if (isValidOption(idx, 0, cmds.size())) {
                return cmds.get(idx);
            }
        } while (true);
    }

    public static boolean isValidOption(int idx, int min, int max) {
        return idx >= min && idx < max;
    }

    private static void printCLIOptions(LinkedList<ICommand> cmds) {
        System.out.println("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t \ntest\n\n");
        for (int i = 1; i < cmds.size(); i++) {
            System.out.println(i + ". " + cmds.get(i));
        }
        System.out.println("0. " + cmds.get(0) + "\n");
    }

}
