/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TD.HTW.App;

import TD.HTW.App.App;
import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    //diese Test Klasse soll nicht getestet werden

}
